import { z } from 'zod';

import { EventSchemas } from './events.ts';

/**
 * Server allow-list derived from the event registry (18 §10, 05 §22.10 `analytics_event_catalog`).
 * `track_events` drops events that are not catalogued and enabled, and `analytics_filter_props`
 * keeps only these prop keys with scalar values.
 */
export interface CatalogEntry {
  event: string;
  allowed_props: string[];
}

/** 05 `analytics_event_catalog.event` check constraint. */
export const EVENT_NAME_PATTERN = /^[a-z][a-z0-9_.]{2,63}$/;

/**
 * 18 §14 rule 1: prop names that would carry special-category data. A `has_*` boolean (presence
 * only, no value) is allowed, e.g. `has_notes`, `has_exemption`.
 */
export const FORBIDDEN_PROP_FRAGMENTS = [
  'allerg',
  'condition',
  'medic',
  'weight',
  'height',
  'bmi',
  'z_',
  'percentile',
  'exemption',
  'notes',
  'text',
  'description',
] as const;

function propKeys(schema: z.ZodTypeAny): string[] {
  let s: z.ZodTypeAny = schema;
  while (s instanceof z.ZodEffects) s = s.innerType();
  if (!(s instanceof z.ZodObject)) throw new Error('analytics event schemas must be z.object');
  return Object.keys(s.shape as Record<string, unknown>).sort();
}

export function analyticsCatalog(): CatalogEntry[] {
  return Object.entries(EventSchemas)
    .map(([event, schema]) => ({ event, allowed_props: propKeys(schema) }))
    .sort((a, b) => a.event.localeCompare(b.event));
}

/** Problems that must fail CI: bad event names and forbidden prop names (18 §14). */
export function catalogViolations(entries: CatalogEntry[] = analyticsCatalog()): string[] {
  const out: string[] = [];
  for (const e of entries) {
    if (!EVENT_NAME_PATTERN.test(e.event)) out.push(`${e.event}: invalid event name`);
    for (const p of e.allowed_props) {
      if (p.startsWith('has_')) continue;
      const hit = FORBIDDEN_PROP_FRAGMENTS.find((f) => p.includes(f));
      if (hit) out.push(`${e.event}.${p}: forbidden prop name (${hit})`);
    }
  }
  return out;
}

/** The seed SQL for `analytics_event_catalog` (idempotent upsert; events removed here are disabled). */
export function catalogSeedSql(entries: CatalogEntry[] = analyticsCatalog()): string {
  const lit = (s: string) => `'${s.replaceAll("'", "''")}'`;
  const rows = entries.map(
    (e) =>
      `  (${lit(e.event)}, array[${e.allowed_props.map(lit).join(', ')}]::text[], true, 'app')`,
  );
  return [
    '-- supabase/seed/catalog/170_analytics_event_catalog.sql',
    '-- GENERATED by tooling/scripts/gen-analytics-catalog.ts from packages/shared/src/analytics/events.ts.',
    '-- Do not edit by hand: change the registry and re-run the generator (18 section 10).',
    '-- Idempotent: upserts every event and its prop allow-list; app events no longer in the registry are',
    '-- disabled (not deleted, so an older app build that still sends them is simply ignored).',
    '',
    'insert into public.analytics_event_catalog (event, allowed_props, enabled, owner) values',
    rows.join(',\n'),
    'on conflict (event) do update',
    '  set allowed_props = excluded.allowed_props, enabled = true, owner = excluded.owner;',
    '',
    'update public.analytics_event_catalog set enabled = false',
    "where owner = 'app' and event not in (",
    entries.map((e) => `  ${lit(e.event)}`).join(',\n'),
    ');',
    '',
  ].join('\n');
}
