-- supabase/seed/catalog/050_ingredient_allergens.sql
-- GENERATED by tooling/scripts/gen-ingredient-seed.py. Allergen links for 040_ingredients.sql
-- (05 section 19 order 5). Idempotent. Dietitian review required with 040.

insert into public.ingredient_allergens (ingredient_id, allergen_id)
select i.id, a.id
from (values
  ('Apricots, dried (khushk khubani)', 'sulphites'),
  ('Chakki atta (whole wheat flour)', 'gluten_cereals'),
  ('Chakki atta (whole wheat flour)', 'wheat'),
  ('Maida (white flour)', 'gluten_cereals'),
  ('Maida (white flour)', 'wheat'),
  ('Whole barley (jau)', 'gluten_cereals'),
  ('Barley flour (jau ka atta)', 'gluten_cereals'),
  ('Oats (jai)', 'gluten_cereals'),
  ('Semolina (sooji)', 'gluten_cereals'),
  ('Semolina (sooji)', 'wheat'),
  ('Vermicelli (seviyan)', 'gluten_cereals'),
  ('Vermicelli (seviyan)', 'wheat'),
  ('Broken wheat (daliya)', 'gluten_cereals'),
  ('Broken wheat (daliya)', 'wheat'),
  ('Roti (chapati), whole wheat', 'gluten_cereals'),
  ('Roti (chapati), whole wheat', 'wheat'),
  ('Naan', 'gluten_cereals'),
  ('Naan', 'wheat'),
  ('Paratha', 'gluten_cereals'),
  ('Paratha', 'wheat'),
  ('White bread (double roti)', 'gluten_cereals'),
  ('White bread (double roti)', 'wheat'),
  ('Peanuts (moongphali)', 'peanuts'),
  ('Eggs, farm', 'eggs'),
  ('Fish, rohu (carp)', 'fish'),
  ('Fish, surmai (king mackerel)', 'fish'),
  ('Prawns (jhinga)', 'crustaceans'),
  ('Tuna, canned in water', 'fish'),
  ('Fresh milk', 'milk'),
  ('Buffalo milk', 'milk'),
  ('Yogurt (dahi)', 'milk'),
  ('Butter (makhan)', 'milk'),
  ('Cream (malai)', 'milk'),
  ('Cheddar cheese', 'milk'),
  ('Mozzarella cheese', 'milk'),
  ('Milk powder', 'milk'),
  ('Condensed milk', 'milk'),
  ('Buttermilk (chhaach)', 'milk'),
  ('Almonds (badam)', 'tree_nuts'),
  ('Walnuts (akhrot)', 'tree_nuts'),
  ('Cashews (kaju)', 'tree_nuts'),
  ('Pistachios (pista)', 'tree_nuts'),
  ('Pine nuts (chilgoza)', 'tree_nuts'),
  ('Sesame seeds (til)', 'sesame'),
  ('Desi ghee', 'milk'),
  ('Mustard seeds (rai)', 'mustard'),
  ('Soy sauce', 'soy'),
  ('Soy sauce', 'gluten_cereals'),
  ('Soy sauce', 'wheat'),
  ('Mayonnaise', 'eggs')
) as v(ingredient_name, allergen_code)
join public.ingredients i on lower(i.name) = lower(v.ingredient_name)
join public.allergens a on a.code = v.allergen_code
on conflict (ingredient_id, allergen_id) do nothing;
