-- supabase/seed/catalog/110_scientific_evidence.sql
-- Content load v1, scientific evidence (S2-13, 05 section 19 order 11, 13 section 10.2). Idempotent:
-- `on conflict (code) do nothing`, so a re-run never overwrites a reviewed row.
--
-- UNREVIEWED. reviewed_by and reviewed_on are null on every row: a nutrition reviewer has not
-- checked the citation, study type, GRADE rating or our summary. Citations are to well-known
-- guidelines, reports and papers; doi and pmid are left null on purpose so `knowledge:validate`
-- fills and cross-checks them from Crossref and PubMed (13 section 9.2) instead of trusting values
-- typed from memory. Summaries are the team's own words (no abstracts copied). summary_i18n has no
-- 'ur' key: Urdu summaries are pending.
-- Not seeded: sci.black_seed.review (13 lists it as "needs selection" by the nutrition reviewer).

insert into public.scientific_evidence (code, title, citation, study_type, grade, summary, summary_i18n, population)
select v.code, v.title, v.citation, v.study_type, v.grade::public.evidence_grade_science, v.summary,
       jsonb_build_object('en', v.summary), v.population
from (values
  ('sci.eating_rate.robinson_2014',
   'Eating rate and energy intake: systematic review and meta-analysis',
   'Robinson E, Almiron-Roig E, Rutters F, de Graaf C, Forde CG, Tudur Smith C, et al. A systematic review and meta-analysis examining the effect of eating rate on energy intake and hunger. Am J Clin Nutr. 2014;100(1):123-51.',
   'meta_analysis', 'moderate',
   'Across controlled studies, eating more slowly led to modestly lower energy intake at the meal, without increasing hunger afterwards.',
   'adults'),
  ('sci.water_preload.dennis_2010',
   'Water before meals during a reduced-energy diet',
   'Dennis EA, Dengo AL, Comber DL, Flack KD, Savla J, Davy KP, et al. Water consumption increases weight loss during a hypocaloric diet intervention in middle-aged and older adults. Obesity (Silver Spring). 2010;18(2):300-7.',
   'rct', 'low',
   'In a 12-week trial, adults who drank about 500 ml of water before each main meal while dieting lost somewhat more weight than those who did not.',
   'adults 55-75 y with overweight'),
  ('sci.family_meals.hammons_2011',
   'Family meal frequency and children''s nutritional health',
   'Hammons AJ, Fiese BH. Is frequency of shared family meals related to the nutritional health of children and adolescents? Pediatrics. 2011;127(6):e1565-74.',
   'meta_analysis', 'low',
   'Children and adolescents who share three or more family meals a week are more likely to have healthier eating patterns and weights; the studies are observational.',
   'children and adolescents'),
  ('sci.repeated_exposure.wardle_2003',
   'Parent-led repeated exposure and vegetable acceptance',
   'Wardle J, Cooke LJ, Gibson EL, Sapochnik M, Sheiham A, Lawson M. Increasing children''s acceptance of vegetables; a randomized trial of parent-led exposure. Appetite. 2003;40(2):155-62.',
   'rct', 'moderate',
   'Offering a small taste of a disliked vegetable daily for about two weeks increased children''s liking and intake more than rewards or no intervention.',
   'children 2-6 y'),
  ('sci.pressure_to_eat.galloway_2006',
   'Pressure to eat and children''s intake',
   'Galloway AT, Fiorito LM, Francis LA, Birch LL. ''Finish your soup'': counterproductive effects of pressuring children to eat on intake and affect. Appetite. 2006;46(3):318-23.',
   'rct', 'low',
   'When children were pressured to finish their food they ate less of it and made more negative comments than when no pressure was applied.',
   'preschool children'),
  ('sci.division_of_responsibility.satter',
   'Division of Responsibility in Feeding',
   'Satter E. Child of Mine: Feeding with Love and Good Sense. Revised ed. Boulder (CO): Bull Publishing; 2000.',
   'expert_opinion', 'expert_opinion',
   'Parents decide what, when and where food is offered; children decide whether and how much to eat. Widely used in paediatric feeding practice.',
   'children'),
  ('sci.olive_oil.predimed_2018',
   'Mediterranean diet with extra-virgin olive oil or nuts and cardiovascular events (PREDIMED)',
   'Estruch R, Ros E, Salas-Salvado J, Covas MI, Corella D, Aros F, et al. Primary prevention of cardiovascular disease with a Mediterranean diet supplemented with extra-virgin olive oil or nuts. N Engl J Med. 2018;378(25):e34.',
   'rct', 'moderate',
   'Among adults at high cardiovascular risk, a Mediterranean diet supplemented with extra-virgin olive oil or nuts lowered the rate of major cardiovascular events compared with a reduced-fat control diet.',
   'adults 55-80 y at high cardiovascular risk'),
  ('sci.barley_beta_glucan.abumweis_2010',
   'Barley beta-glucan and blood lipids: meta-analysis',
   'AbuMweis SS, Jew S, Ames NP. Beta-glucan from barley and its lipid-lowering capacity: a meta-analysis of randomized, controlled trials. Eur J Clin Nutr. 2010;64(12):1472-80.',
   'meta_analysis', 'moderate',
   'Barley beta-glucan, at intakes of a few grams a day, lowered total and LDL cholesterol modestly in randomised trials.',
   'adults'),
  ('sci.free_sugars.who_2015',
   'WHO guideline on sugars intake',
   'World Health Organization. Guideline: sugars intake for adults and children. Geneva: WHO; 2015.',
   'guideline', 'moderate',
   'Free sugars (including those in honey, syrups and juices) should be below 10 percent of energy intake, with a further reduction to below 5 percent suggested.',
   'adults and children'),
  ('sci.infant_botulism.honey',
   'No honey for infants under 12 months (infant botulism)',
   'Centers for Disease Control and Prevention. Botulism: infant botulism prevention guidance (do not give honey to children younger than 12 months). Atlanta (GA): CDC.',
   'guideline', 'expert_opinion',
   'Honey can carry Clostridium botulinum spores; infants under 12 months should not be given honey in any form, including in cooking or on dummies.',
   'infants under 12 months'),
  ('sci.dates_composition.alfarsi_2008',
   'Nutritional properties of dates',
   'Al-Farsi MA, Lee CY. Nutritional and functional properties of dates: a review. Crit Rev Food Sci Nutr. 2008;48(10):877-87.',
   'narrative_review', 'expert_opinion',
   'Dates are energy-dense, mostly sugars, and provide fibre, potassium and polyphenols; amounts vary by variety and ripeness.',
   'general'),
  ('sci.vinegar_glycemia.shishehbor_2017',
   'Vinegar with meals and post-meal glucose: meta-analysis',
   'Shishehbor F, Mansoori A, Shirani F. Vinegar consumption can attenuate postprandial glucose and insulin responses; a systematic review and meta-analysis of clinical trials. Diabetes Res Clin Pract. 2017;127:1-9.',
   'meta_analysis', 'low',
   'Small trials suggest vinegar taken with a meal can modestly reduce the rise in blood glucose and insulin after the meal.',
   'adults with and without diabetes'),
  ('sci.pomegranate_bp.sahebkar_2017',
   'Pomegranate juice and blood pressure: meta-analysis',
   'Sahebkar A, Ferri C, Giorgini P, Bo S, Nachtigal P, Grassi D. Effects of pomegranate juice on blood pressure: a systematic review and meta-analysis of randomized controlled trials. Pharmacol Res. 2017;115:149-61.',
   'meta_analysis', 'low',
   'Pomegranate juice produced small reductions in blood pressure in short trials; the evidence is limited and juice is a source of free sugars.',
   'adults'),
  ('sci.whole_fruit_t2d.muraki_2013',
   'Whole fruit, fruit juice and type 2 diabetes risk',
   'Muraki I, Imamura F, Manson JE, Hu FB, Willett WC, van Dam RM, et al. Fruit consumption and risk of type 2 diabetes: results from three prospective longitudinal cohort studies. BMJ. 2013;347:f5001.',
   'cohort', 'low',
   'Higher intake of whole fruits such as grapes and apples was associated with lower risk of type 2 diabetes, while fruit juice was associated with higher risk.',
   'adults (US health professionals)'),
  ('sci.veg_energy_density.ledoux_2011',
   'Fruit and vegetable intake and adiposity',
   'Ledoux TA, Hingle MD, Baranowski T. Relationship of fruit and vegetable intake with adiposity: a systematic review. Obes Rev. 2011;12(5):e143-50.',
   'systematic_review', 'low',
   'Evidence that eating more fruit and vegetables lowers adiposity is limited and mixed; benefits are more likely when they replace energy-dense foods.',
   'children and adults'),
  ('sci.dairy_calcium.iom_2011',
   'Dietary Reference Intakes for calcium and vitamin D',
   'Institute of Medicine. Dietary Reference Intakes for Calcium and Vitamin D. Washington (DC): National Academies Press; 2011.',
   'guideline', 'high',
   'Sets age-specific calcium and vitamin D intakes for bone health; milk and yogurt are major calcium sources in most diets.',
   'all ages'),
  ('sci.ramadan_body_comp.fernando_2019',
   'Ramadan fasting and body composition: meta-analysis',
   'Fernando HA, Zibellini J, Harris RA, Seimon RV, Sainsbury A. Effect of Ramadan fasting on weight and body composition in healthy non-athlete adults: a systematic review and meta-analysis. Nutrients. 2019;11(2):478.',
   'meta_analysis', 'low',
   'Ramadan fasting led to small losses of weight and fat mass in healthy adults that were largely regained within weeks after Ramadan.',
   'healthy non-athlete adults'),
  ('sci.diabetes_ramadan.idf_dar_2021',
   'Diabetes and Ramadan practical guidelines',
   'International Diabetes Federation and DAR International Alliance. Diabetes and Ramadan: Practical Guidelines 2021. Brussels: IDF; 2021.',
   'guideline', 'expert_opinion',
   'People with diabetes should have a risk assessment with their clinician before Ramadan; those on insulin or sulfonylureas are at higher risk of hypoglycaemia while fasting.',
   'people with diabetes'),
  ('sci.tea_iron.hurrell_1999',
   'Polyphenol beverages and non-haem iron absorption',
   'Hurrell RF, Reddy M, Cook JD. Inhibition of non-haem iron absorption in man by polyphenolic-containing beverages. Br J Nutr. 1999;81(4):289-95.',
   'rct', 'moderate',
   'Black tea and other polyphenol-rich drinks taken with a meal markedly reduced absorption of non-haem iron from that meal.',
   'adults'),
  ('sci.water_needs.efsa_2010',
   'Dietary Reference Values for water',
   'EFSA Panel on Dietetic Products, Nutrition and Allergies. Scientific Opinion on Dietary Reference Values for water. EFSA J. 2010;8(3):1459.',
   'guideline', 'moderate',
   'Sets adequate total water intakes by age and sex (for example about 2.0 l/day for women and 2.5 l/day for men from all drinks and food), with higher needs in heat, pregnancy and lactation.',
   'all ages'),
  ('sci.food_waste.fao_2019',
   'Food loss and waste',
   'Food and Agriculture Organization of the United Nations. The State of Food and Agriculture 2019: Moving forward on food loss and waste reduction. Rome: FAO; 2019.',
   'guideline', 'expert_opinion',
   'A large share of food is lost or wasted along the supply chain and in households; planning, storage and using leftovers reduce household waste.',
   'general'),
  ('sci.responsive_feeding.paho_who_2003',
   'Responsive feeding of young children',
   'Pan American Health Organization, World Health Organization. Guiding principles for complementary feeding of the breastfed child. Washington (DC): PAHO; 2003.',
   'guideline', 'expert_opinion',
   'Feed young children responsively: respond to hunger and fullness cues, feed slowly and patiently, encourage without forcing, and minimise distractions at meals.',
   'children 6-24 months'),
  ('sci.fibre_intake.reynolds_2019',
   'Carbohydrate quality, fibre and whole grains',
   'Reynolds A, Mann J, Cummings J, Winter N, Mete E, Te Morenga L. Carbohydrate quality and human health: a series of systematic reviews and meta-analyses. Lancet. 2019;393(10170):434-45.',
   'meta_analysis', 'moderate',
   'Higher intakes of dietary fibre and whole grains were associated with lower risk of heart disease, type 2 diabetes and several cancers, with the largest benefits at 25-29 g fibre a day or more.',
   'adults'),
  ('sci.sodium.who_2012',
   'WHO guideline on sodium intake',
   'World Health Organization. Guideline: sodium intake for adults and children. Geneva: WHO; 2012.',
   'guideline', 'moderate',
   'Adults should eat less than 2 g sodium (5 g salt) a day, with lower amounts for children adjusted to their energy needs.',
   'adults and children'),
  ('sci.diet_chronic_disease.who_fao_2003',
   'Diet, nutrition and the prevention of chronic diseases',
   'World Health Organization, Food and Agriculture Organization. Diet, nutrition and the prevention of chronic diseases. Report of a joint WHO/FAO expert consultation. WHO Technical Report Series 916. Geneva: WHO; 2003.',
   'guideline', 'expert_opinion',
   'Population goals for fats, free sugars, salt, fruit and vegetables and physical activity to reduce chronic disease risk.',
   'general population'),
  ('sci.dietary_guidelines.usda_2020',
   'Dietary Guidelines for Americans 2020-2025',
   'US Department of Agriculture, US Department of Health and Human Services. Dietary Guidelines for Americans, 2020-2025. 9th ed. Washington (DC); 2020.',
   'guideline', 'expert_opinion',
   'Life-stage dietary guidance: nutrient-dense foods, limits on added sugars, saturated fat and sodium, and no added sugars before age 2.',
   'all ages from birth'),
  ('sci.water_electrolytes.iom_2005',
   'Dietary Reference Intakes for water, potassium, sodium, chloride and sulfate',
   'Institute of Medicine. Dietary Reference Intakes for Water, Potassium, Sodium, Chloride, and Sulfate. Washington (DC): National Academies Press; 2005.',
   'guideline', 'moderate',
   'Sets adequate intakes for total water and electrolytes by life stage, including pregnancy and lactation.',
   'all ages'),
  ('sci.energy_macros.iom_2005',
   'Dietary Reference Intakes for energy and macronutrients',
   'Institute of Medicine. Dietary Reference Intakes for Energy, Carbohydrate, Fiber, Fat, Fatty Acids, Cholesterol, Protein, and Amino Acids. Washington (DC): National Academies Press; 2005.',
   'guideline', 'high',
   'Estimated energy requirement equations by age, sex and activity (including children, pregnancy and lactation) and acceptable macronutrient ranges.',
   'all ages'),
  ('sci.ree_equation.mifflin_1990',
   'Mifflin-St Jeor resting energy expenditure equation',
   'Mifflin MD, St Jeor ST, Hill LA, Scott BJ, Daugherty SA, Koh YO. A new predictive equation for resting energy expenditure in healthy individuals. Am J Clin Nutr. 1990;51(2):241-7.',
   'cross_sectional', 'moderate',
   'Derived an equation estimating resting energy expenditure from weight, height, age and sex in healthy adults; used for adult energy estimates.',
   'healthy adults 19-78 y'),
  ('sci.growth_standards.who_2006',
   'WHO Child Growth Standards',
   'WHO Multicentre Growth Reference Study Group. WHO Child Growth Standards: length/height-for-age, weight-for-age, weight-for-length, weight-for-height and body mass index-for-age: methods and development. Geneva: WHO; 2006.',
   'guideline', 'high',
   'International standards describing how healthy children under five should grow, used to judge growth with z-scores and percentiles.',
   'children 0-5 y'),
  ('sci.exposure_review.cooke_2007',
   'Exposure and healthy eating in childhood',
   'Cooke L. The importance of exposure for healthy eating in childhood: a review. J Hum Nutr Diet. 2007;20(4):294-301.',
   'narrative_review', 'expert_opinion',
   'Repeated, pressure-free exposure is one of the most reliable ways to increase children''s acceptance of new foods; many exposures may be needed.',
   'children'),
  ('sci.exposure_toddlers.birch_1982',
   'Exposure and two-year-olds'' food preferences',
   'Birch LL, Marlin DW. I don''t like it; I never tried it: effects of exposure on two-year-old children''s food preferences. Appetite. 1982;3(4):353-60.',
   'rct', 'low',
   'Toddlers'' preference for unfamiliar fruits and cheeses increased with the number of times they had been offered them.',
   'children about 2 y')
) as v(code, title, citation, study_type, grade, summary, population)
on conflict (code) do nothing;
