-- supabase/seed/catalog/120_recommendations.sql
-- Content load v1, recommendations and the adab set (S2-13, FR-ISL-01, FR-ISL-07; 05 section 19
-- order 11; 13 section 10.3). Idempotent (`on conflict (code) do nothing`, `where not exists`).
--
-- Every recommendation is inserted `unverified` and STAYS unverified here: 05 section 19 publishes
-- by updating to 'verified' so the gate checks it, but none of the linked Islamic sources is
-- verified yet (100_islamic_sources.sql), so publishing would fail the gate, and the content has
-- not been through scholar or nutrition review. Users see none of these rows (RLS: verified only).
-- public.recommendation_completeness() lists what each row still needs.
--
-- Review items:
--   * practical_text_i18n and title_i18n have English only. No 'ur' text was written; the Urdu copy
--     editor and an Urdu-speaking reviewer supply it (the publishing gate requires 'ur').
--   * tradition_scope follows the sources actually linked: rows with a Qur'anic (shared) source get
--     {shared,sunni,shia}; rows resting only on Sunni hadith get {sunni}, until a verified Shia
--     source on the same practice is added (13 section 10.3 note; 13 listed some of these as
--     {shared,sunni}, which the 0019a gate would reject for 'shared' without a shared source).
--   * Dropped from 13's list of 34: rec.food.black_seed_culinary (no evidence row selected yet) and
--     rec.food.dates_ajwa_context (context-only narration with a protective claim; left for the
--     scholar and nutrition reviewers to decide). Shia narration links from 13 are not seeded.
--   * The adab set (FR-ISL-07, onboarding step 2 and the Learn tab) is tagged
--     applies_to.collections = ["adab"], with a child-friendly script in each text.

insert into public.recommendations (code, title_i18n, practical_text_i18n, applies_to, contraindications,
                                    tradition_scope, science_only, review_status)
select v.code, jsonb_build_object('en', v.title), jsonb_build_object('en', v.body), v.applies::jsonb,
       v.contra::jsonb, v.scope::public.source_tradition[], false, 'unverified'
from (values
  ('rec.thuluth.core', 'The rule of thirds at every meal',
   'Fill half the plate with vegetables and fruit, a quarter with protein and a quarter with whole grains. Have a glass of water 20 to 30 minutes before eating, small sips during, and drink freely afterwards. Take about 20 minutes over the meal and stop when comfortably satisfied, around 70 to 80 percent full. For children the rule of thirds is about rhythm: regular meals, eating together, slowing down, and seconds whenever they are still hungry.',
   '{"life_stages":["toddler","child","teen","adult","older_adult"],"collections":["thuluth"]}', '{}', '{shared,sunni,shia}'),
  ('rec.thuluth.fullness_check', 'Pause before seconds',
   'Before a second serving, pause and ask yourself: am I still hungry, or just enjoying the taste? Wait about 15 minutes, have some water, then decide. This check is for adults only; children may always have seconds when hungry.',
   '{"life_stages":["adult","older_adult"]}', '{"modules":["eating_concern"]}', '{sunni}'),
  ('rec.thuluth.slow_eating', 'Eat slowly',
   'Put the spoon or roti down between bites, chew well and aim for about 20 minutes per meal. For children: sit together at the table, screens away, and no rushing.',
   '{"life_stages":["toddler","child","teen","adult","older_adult"]}', '{}', '{shared,sunni,shia}'),
  ('rec.thuluth.fluid_timing', 'Water before, sips during, drink after',
   'Have a glass of water 20 to 30 minutes before meals, small sips during the meal, and drink freely 30 to 60 minutes after. For children: keep water on the table, and offer milk after meals rather than before so it does not fill them up first.',
   '{"life_stages":["child","teen","adult","older_adult"]}', '{}', '{sunni}'),
  ('rec.etiquette.bismillah_right_hand', 'Bismillah, right hand, from what is in front of you',
   'Start each meal with Bismillah, eat with the right hand, and eat from the part of the dish in front of you. Child script: "Bismillah first, right hand, and my side of the plate."',
   '{"collections":["adab"],"min_age_months":12}', '{}', '{sunni}'),
  ('rec.etiquette.no_criticising_food', 'No criticising food',
   'Food is never criticised at the table: if you like it, eat it; if not, leave it without comment. Family script: "No thank you" is allowed, "yuck" is not. Never force a child to finish their plate.',
   '{"collections":["adab"]}', '{}', '{sunni}'),
  ('rec.etiquette.drink_in_breaths', 'Drink in three breaths',
   'Sit to drink and take water in three sips, breathing outside the cup between sips. It slows drinking down and builds a steady water habit. Child script: "Sip, breathe, sip, breathe, sip."',
   '{"collections":["adab"],"min_age_months":24}', '{}', '{sunni}'),
  ('rec.etiquette.eat_together', 'Eat together',
   'Eat at least one meal a day together at the table, starting with Bismillah, with conversation and screens put away.',
   '{"collections":["adab"]}', '{}', '{sunni}'),
  ('rec.etiquette.praise_after_eating', 'Praise Allah after eating',
   'End the meal with Alhamdulillah and thank whoever cooked. Child script: "Alhamdulillah, and thank you for the food."',
   '{"collections":["adab"]}', '{}', '{sunni}'),
  ('rec.moderation.share_food', 'Food for two is enough for three',
   'Serve modestly from the pot, share with others and invite guests; cook what the family will eat rather than more. Child script: "There is always enough to share."',
   '{"collections":["adab"]}', '{}', '{shared,sunni,shia}'),
  ('rec.moderation.one_intestine', 'Eat for nourishment',
   'Treat meals as nourishment, not a contest, and avoid eating past comfortable fullness. This guidance is for adults only.',
   '{"life_stages":["adult","older_adult"]}', '{"modules":["eating_concern"]}', '{shared,sunni,shia}'),
  ('rec.waste.no_waste', 'Waste nothing',
   'Plan leftovers on purpose (cook once, eat twice), serve small portions and refill rather than scrape plates into the bin, and pick up and eat a fallen piece once it is cleaned.',
   '{}', '{}', '{shared,sunni,shia}'),
  ('rec.halal_tayyib.whole_foods', 'Halal and wholesome',
   'Choose food that is halal and wholesome: home-cooked meals, whole grains and fresh produce, with fewer ultra-processed snacks and sugary drinks. Check for a trusted halal certification or butcher for meat.',
   '{}', '{}', '{shared,sunni,shia}'),
  ('rec.gratitude.look_at_food', 'Look at your food',
   'Before eating, name one thing on the plate and where it came from. It is a moment of gratitude and mindful eating that children enjoy.',
   '{}', '{}', '{shared,sunni,shia}'),
  ('rec.food.dates_daily', 'Dates as the family sweetener',
   'Use dates as the family''s natural sweetener: about 2 to 3 a day for adults and 1 to 2 for children. Chop them small for children under 5 (choking risk). Dates count as carbohydrate for anyone with diabetes.',
   '{"min_age_months":12}', '{}', '{shared,sunni,shia}'),
  ('rec.food.dates_with_cucumber', 'Dates with cucumber',
   'Pair sweet foods with water-rich vegetables: dates with cucumber or salad at snack time.',
   '{"min_age_months":12}', '{}', '{sunni}'),
  ('rec.food.honey', 'Honey in measured amounts',
   'Use honey in measured teaspoons (about 1 tsp for adults, half a tsp for children) in yogurt or talbina; it counts as sugar. Never give honey to babies under 12 months. No medical effect is claimed.',
   '{"min_age_months":12}', '{"life_stages":["infant"]}', '{shared,sunni,shia}'),
  ('rec.food.talbina', 'A weekly talbina breakfast',
   'Make a weekly barley talbina breakfast: 2 to 3 tbsp roasted barley flour per person simmered in milk and water and sweetened with chopped dates. A warm, comforting, fibre-rich food; make it smooth for toddlers.',
   '{"min_age_months":12}', '{"allergens":["gluten_cereals","milk"]}', '{sunni}'),
  ('rec.food.barley_in_atta', 'Barley in the roti',
   'Mix 10 to 20 percent barley flour into roti atta, and add barley to soups and haleem.',
   '{}', '{"allergens":["gluten_cereals"]}', '{sunni}'),
  ('rec.food.olive_oil', 'Olive oil, measured',
   'Use olive oil raw on salads, chana and daal, and keep total cooking oil measured, about 1 tsp per person per dish.',
   '{}', '{}', '{shared,sunni,shia}'),
  ('rec.food.milk', 'Milk and yogurt for calcium',
   'Make milk and yogurt the main calcium source. Give milk after meals so it does not fill children up first. Whole cow''s milk as a main drink only from 12 months. Say the milk du''a together with children.',
   '{"min_age_months":12}', '{"allergens":["milk"]}', '{shared,sunni,shia}'),
  ('rec.food.pomegranate_whole', 'Pomegranate as whole fruit',
   'Prefer the whole fruit, for example arils in fruit chaat or raita, over juice. Arils are a choking risk under 4 years unless crushed.',
   '{"min_age_months":12}', '{}', '{shared,sunni,shia}'),
  ('rec.food.gourd_weekly', 'Gourd every week',
   'Include lauki, kaddu or another gourd every week: low-cost, water-rich vegetables that add volume to meals. A smooth gourd curry or soup is a good first vegetable for picky eaters.',
   '{}', '{}', '{sunni}'),
  ('rec.food.vinegar_condiment', 'Vinegar as a condiment',
   'Dress kachumber and salads with vinegar and lemon instead of creamy dressings.',
   '{"min_age_months":36}', '{}', '{sunni}'),
  ('rec.food.figs', 'Figs as a snack',
   'Offer soaked dried figs as a fibre-rich snack: 1 to 2 for children, chopped small for young children.',
   '{"min_age_months":12}', '{}', '{shared,sunni,shia}'),
  ('rec.food.grapes_whole', 'Whole grapes, not juice',
   'Choose whole grapes rather than grape juice. Quarter grapes lengthwise for children under 5 (choking risk).',
   '{"min_age_months":12}', '{}', '{shared,sunni,shia}'),
  ('rec.fasting.suhoor_blessing', 'Never skip suhoor',
   'Do not skip suhoor: include protein, whole grains and fluids (for example eggs, roti, yogurt and water) to carry the fasting day.',
   '{"contexts":["fasting"]}', '{}', '{shared,sunni,shia}'),
  ('rec.fasting.late_suhoor', 'Take suhoor close to Fajr',
   'Take suhoor close to Fajr, within the timetable your household follows, to shorten the fasting gap.',
   '{"contexts":["fasting"]}', '{}', '{sunni}'),
  ('rec.fasting.iftar_dates_water', 'Break the fast with dates and water',
   'Break the fast promptly with 1 to 3 dates and water, pray Maghrib, then eat a balanced plate. Go easy on fried pakoras and sugary sherbet.',
   '{"contexts":["fasting"]}', '{}', '{sunni}'),
  ('rec.fasting.ease_and_exemption', 'Fasting and ease',
   'Allah intends ease. If you are pregnant, breastfeeding, ill, on insulin or sulfonylureas, or deciding for a young child, decide together with your clinician and a scholar you trust; the app supports whatever you decide. The app does not give rulings.',
   '{"contexts":["fasting"]}', '{}', '{shared,sunni,shia}'),
  ('rec.fasting.children_practice', 'Children and practice fasts',
   'No fasting under 7. From 7 until puberty, parents may choose optional short practice fasts, with water and a meal the moment the child feels dizzy, unusually tired or upset.',
   '{"contexts":["fasting"],"life_stages":["child"],"min_age_months":84}', '{}', '{shared,sunni,shia}'),
  ('rec.pregnancy.dates_late_pregnancy', 'Dates in pregnancy',
   'Dates are a nourishing snack in pregnancy as part of normal meals. With gestational diabetes, count them in the carbohydrate plan agreed with your clinician. No effect on labour is claimed.',
   '{"modules":["pregnancy"]}', '{}', '{shared,sunni,shia}'),
  ('rec.iron.tea_timing', 'Chai after, not with, meals',
   'Have chai at least an hour after meals, and pair iron-rich foods (beef, lentils, chickpeas, spinach) with vitamin C foods such as lemon, guava or tomato.',
   '{"life_stages":["teen","adult","older_adult"]}', '{}', '{shared,sunni,shia}')
) as v(code, title, body, applies, contra, scope)
on conflict (code) do nothing;

-- Evidence links (S = supports, C = context; science rows 'supports' unless marked caution) ------------
insert into public.recommendation_evidence (recommendation_id, islamic_source_id, scientific_evidence_id, relationship)
select r.id, s.id, e.id, v.relationship
from (values
  ('rec.thuluth.core', 'hadith.tirmidhi.2380', null, 'supports'),
  ('rec.thuluth.core', 'quran.7.31', null, 'supports'),
  ('rec.thuluth.core', null, 'sci.eating_rate.robinson_2014', 'supports'),
  ('rec.thuluth.core', null, 'sci.water_preload.dennis_2010', 'supports'),
  ('rec.thuluth.fullness_check', 'hadith.tirmidhi.2380', null, 'supports'),
  ('rec.thuluth.fullness_check', null, 'sci.eating_rate.robinson_2014', 'supports'),
  ('rec.thuluth.slow_eating', 'quran.7.31', null, 'supports'),
  ('rec.thuluth.slow_eating', null, 'sci.eating_rate.robinson_2014', 'supports'),
  ('rec.thuluth.slow_eating', null, 'sci.responsive_feeding.paho_who_2003', 'supports'),
  ('rec.thuluth.fluid_timing', 'hadith.tirmidhi.2380', null, 'supports'),
  ('rec.thuluth.fluid_timing', 'hadith.muslim.2028', null, 'supports'),
  ('rec.thuluth.fluid_timing', null, 'sci.water_preload.dennis_2010', 'supports'),
  ('rec.thuluth.fluid_timing', null, 'sci.water_needs.efsa_2010', 'supports'),
  ('rec.etiquette.bismillah_right_hand', 'hadith.bukhari.5376', null, 'supports'),
  ('rec.etiquette.bismillah_right_hand', 'hadith.muslim.2020', null, 'supports'),
  ('rec.etiquette.bismillah_right_hand', null, 'sci.responsive_feeding.paho_who_2003', 'supports'),
  ('rec.etiquette.no_criticising_food', 'hadith.bukhari.5409', null, 'supports'),
  ('rec.etiquette.no_criticising_food', null, 'sci.pressure_to_eat.galloway_2006', 'supports'),
  ('rec.etiquette.no_criticising_food', null, 'sci.division_of_responsibility.satter', 'supports'),
  ('rec.etiquette.drink_in_breaths', 'hadith.muslim.2028', null, 'supports'),
  ('rec.etiquette.drink_in_breaths', 'hadith.bukhari.5630', null, 'supports'),
  ('rec.etiquette.drink_in_breaths', null, 'sci.water_needs.efsa_2010', 'supports'),
  ('rec.etiquette.eat_together', 'hadith.abu_dawud.3764', null, 'supports'),
  ('rec.etiquette.eat_together', null, 'sci.family_meals.hammons_2011', 'supports'),
  ('rec.etiquette.praise_after_eating', 'hadith.bukhari.5458', null, 'supports'),
  ('rec.etiquette.praise_after_eating', 'hadith.muslim.2734', null, 'supports'),
  ('rec.etiquette.praise_after_eating', null, 'sci.family_meals.hammons_2011', 'context'),
  ('rec.moderation.share_food', 'hadith.bukhari.5392', null, 'supports'),
  ('rec.moderation.share_food', 'hadith.muslim.2059', null, 'supports'),
  ('rec.moderation.share_food', 'quran.6.141', null, 'supports'),
  ('rec.moderation.share_food', null, 'sci.food_waste.fao_2019', 'supports'),
  ('rec.moderation.one_intestine', 'hadith.bukhari.5393', null, 'context'),
  ('rec.moderation.one_intestine', 'quran.20.81', null, 'supports'),
  ('rec.moderation.one_intestine', null, 'sci.eating_rate.robinson_2014', 'supports'),
  ('rec.waste.no_waste', 'hadith.muslim.2033', null, 'supports'),
  ('rec.waste.no_waste', 'quran.7.31', null, 'supports'),
  ('rec.waste.no_waste', null, 'sci.food_waste.fao_2019', 'supports'),
  ('rec.halal_tayyib.whole_foods', 'quran.2.168', null, 'supports'),
  ('rec.halal_tayyib.whole_foods', 'quran.2.172', null, 'supports'),
  ('rec.halal_tayyib.whole_foods', null, 'sci.fibre_intake.reynolds_2019', 'supports'),
  ('rec.halal_tayyib.whole_foods', null, 'sci.free_sugars.who_2015', 'supports'),
  ('rec.gratitude.look_at_food', 'quran.80.24_32', null, 'supports'),
  ('rec.gratitude.look_at_food', 'quran.2.172', null, 'supports'),
  ('rec.gratitude.look_at_food', 'hadith.muslim.2734', null, 'context'),
  ('rec.gratitude.look_at_food', null, 'sci.responsive_feeding.paho_who_2003', 'supports'),
  ('rec.food.dates_daily', 'hadith.muslim.2046', null, 'supports'),
  ('rec.food.dates_daily', 'quran.55.68', null, 'supports'),
  ('rec.food.dates_daily', null, 'sci.dates_composition.alfarsi_2008', 'supports'),
  ('rec.food.dates_daily', null, 'sci.free_sugars.who_2015', 'caution'),
  ('rec.food.dates_with_cucumber', 'hadith.bukhari.5440', null, 'supports'),
  ('rec.food.dates_with_cucumber', null, 'sci.dates_composition.alfarsi_2008', 'supports'),
  ('rec.food.honey', 'quran.16.69', null, 'context'),
  ('rec.food.honey', 'hadith.bukhari.5684', null, 'context'),
  ('rec.food.honey', null, 'sci.free_sugars.who_2015', 'caution'),
  ('rec.food.honey', null, 'sci.infant_botulism.honey', 'caution'),
  ('rec.food.talbina', 'hadith.bukhari.5417', null, 'supports'),
  ('rec.food.talbina', null, 'sci.barley_beta_glucan.abumweis_2010', 'supports'),
  ('rec.food.barley_in_atta', 'hadith.bukhari.5413', null, 'supports'),
  ('rec.food.barley_in_atta', null, 'sci.barley_beta_glucan.abumweis_2010', 'supports'),
  ('rec.food.barley_in_atta', null, 'sci.fibre_intake.reynolds_2019', 'supports'),
  ('rec.food.olive_oil', 'quran.24.35', null, 'supports'),
  ('rec.food.olive_oil', 'quran.95.1', null, 'supports'),
  ('rec.food.olive_oil', 'hadith.tirmidhi.1851', null, 'supports'),
  ('rec.food.olive_oil', null, 'sci.olive_oil.predimed_2018', 'supports'),
  ('rec.food.milk', 'quran.16.66', null, 'supports'),
  ('rec.food.milk', 'hadith.tirmidhi.3455', null, 'supports'),
  ('rec.food.milk', null, 'sci.dairy_calcium.iom_2011', 'supports'),
  ('rec.food.pomegranate_whole', 'quran.55.68', null, 'supports'),
  ('rec.food.pomegranate_whole', 'quran.6.141', null, 'supports'),
  ('rec.food.pomegranate_whole', null, 'sci.pomegranate_bp.sahebkar_2017', 'context'),
  ('rec.food.pomegranate_whole', null, 'sci.whole_fruit_t2d.muraki_2013', 'supports'),
  ('rec.food.gourd_weekly', 'hadith.bukhari.5379', null, 'supports'),
  ('rec.food.gourd_weekly', null, 'sci.veg_energy_density.ledoux_2011', 'supports'),
  ('rec.food.gourd_weekly', null, 'sci.repeated_exposure.wardle_2003', 'supports'),
  ('rec.food.vinegar_condiment', 'hadith.muslim.2052', null, 'supports'),
  ('rec.food.vinegar_condiment', null, 'sci.vinegar_glycemia.shishehbor_2017', 'supports'),
  ('rec.food.figs', 'quran.95.1', null, 'supports'),
  ('rec.food.figs', null, 'sci.fibre_intake.reynolds_2019', 'supports'),
  ('rec.food.grapes_whole', 'quran.80.24_32', null, 'supports'),
  ('rec.food.grapes_whole', 'quran.6.141', null, 'supports'),
  ('rec.food.grapes_whole', null, 'sci.whole_fruit_t2d.muraki_2013', 'supports'),
  ('rec.fasting.suhoor_blessing', 'hadith.bukhari.1923', null, 'supports'),
  ('rec.fasting.suhoor_blessing', 'quran.2.187', null, 'supports'),
  ('rec.fasting.suhoor_blessing', null, 'sci.ramadan_body_comp.fernando_2019', 'context'),
  ('rec.fasting.suhoor_blessing', null, 'sci.water_needs.efsa_2010', 'supports'),
  ('rec.fasting.late_suhoor', 'hadith.bukhari.1921', null, 'supports'),
  ('rec.fasting.late_suhoor', null, 'sci.water_needs.efsa_2010', 'supports'),
  ('rec.fasting.iftar_dates_water', 'hadith.abu_dawud.2356', null, 'supports'),
  ('rec.fasting.iftar_dates_water', 'hadith.bukhari.1957', null, 'supports'),
  ('rec.fasting.iftar_dates_water', null, 'sci.dates_composition.alfarsi_2008', 'supports'),
  ('rec.fasting.iftar_dates_water', null, 'sci.water_needs.efsa_2010', 'supports'),
  ('rec.fasting.ease_and_exemption', 'quran.2.183_185', null, 'supports'),
  ('rec.fasting.ease_and_exemption', null, 'sci.diabetes_ramadan.idf_dar_2021', 'supports'),
  ('rec.fasting.children_practice', 'quran.2.183_185', null, 'context'),
  ('rec.fasting.children_practice', null, 'sci.water_needs.efsa_2010', 'supports'),
  ('rec.fasting.children_practice', null, 'sci.responsive_feeding.paho_who_2003', 'context'),
  ('rec.pregnancy.dates_late_pregnancy', 'quran.19.25_26', null, 'context'),
  ('rec.pregnancy.dates_late_pregnancy', null, 'sci.dates_composition.alfarsi_2008', 'supports'),
  ('rec.iron.tea_timing', 'quran.2.168', null, 'supports'),
  ('rec.iron.tea_timing', 'hadith.muslim.2046', null, 'context'),
  ('rec.iron.tea_timing', null, 'sci.tea_iron.hurrell_1999', 'supports')
) as v(rec_code, source_code, sci_code, relationship)
join public.recommendations r on r.code = v.rec_code
left join public.islamic_sources s on s.code = v.source_code
left join public.scientific_evidence e on e.code = v.sci_code
where (v.source_code is null or s.id is not null)
  and (v.sci_code is null or e.id is not null)
  and not exists (select 1 from public.recommendation_evidence x
                  where x.recommendation_id = r.id
                    and x.islamic_source_id is not distinct from s.id
                    and x.scientific_evidence_id is not distinct from e.id);
